### ISSUE TITLE
Add support for customizing IP settings

### ISSUE THREAD

**Issue by lmmz** [UpCloudLtd/upcloud-packer#15]
Currently there's hardcoded IPAddresses entry to deploy every server with a Private IPv4, Public IPv4 and Public IPv6 address. It should be possible to define any combination of IPs and their types (e.g. only private IPv4 address or only public IPv4 + public IPv6 or multiple public IPv4s).

**Comment by ilijamt** [comment]
Added support for this in #16

**Comment by maxfrei** [comment]
Fixed in https://github.com/UpCloudLtd/upcloud-packer/pull/26
