### ISSUE TITLE
Add support to ability provide plan

### ISSUE THREAD

**Issue by moredure** [UpCloudLtd/upcloud-packer#18]

**Comment by Raiou** [comment]
Hi there, could you elaborate a little what you mean? Packer is intended for generating cloud server templates which can then be deployed using the desired plan. The default plan should be adequate for the build process.

**Comment by moredure** [comment]
Sometimes default plan may not fit well

**Comment by moredure** [comment]
@Raiou please check https://github.com/UpCloudLtd/upcloud-packer/issues/19
